/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class WhCatTimer {
  constructor(config?: TimerConfigInput | undefined | null)
  scheduleOnce(runAtMs: number, payloadJson?: string | undefined | null, jobId?: string | undefined | null): ScheduleResult
  scheduleInterval(everyMs: number, payloadJson?: string | undefined | null, jobId?: string | undefined | null, strictIntervalCycle?: boolean | undefined | null, count?: number | undefined | null): ScheduleResult
  scheduleCron(cronExpr: string, tz?: string | undefined | null, payloadJson?: string | undefined | null, jobId?: string | undefined | null, count?: number | undefined | null): ScheduleResult
  schedule(input: NapiScheduleInput): ScheduleResult
  cancelJob(jobId: string): boolean
  pauseJob(jobId: string): void
  resumeJob(jobId: string): void
  getNextRuns(jobId: string, count: number): Array<number>
  getJobSchedule(jobId: string, count?: number | undefined | null): NapiJobSchedule
  listJobs(): Array<NapiJobListItem>
  getJob(jobId: string): NapiJobListItem
  restore(): number
  drainExecutionRecords(limit: number): Array<NapiExecutionRecord>
  queryExecutionRecords(limit: number): Array<NapiExecutionRecord>
  drainAuditLogs(limit: number): Array<NapiAuditRecord>
  queryAuditLogs(limit: number): Array<NapiAuditRecord>
  shutdown(): void
}

export declare function dailyAt(hour: number, minute: number): string

export declare function everyHours(n: number): string

export declare function everyMinutes(n: number): string

export declare function monthlyOn(day: number, hour: number, minute: number): string

export interface NapiAuditRecord {
  timestampMs: number
  event: string
  detailJson: string
}

export interface NapiExecutionRecord {
  id: string
  jobId: string
  plannedTimeMs: number
  actualTimeMs: number
  status: string
  error?: string
}

export interface NapiJobListItem {
  jobId: string
  jobType: string
  state: string
  enabled: boolean
  strictIntervalCycle: boolean
  maxRuns?: number
  runCount: number
  runAtMs?: number
  everyMs?: number
  cronExpr?: string
  tz?: string
  lastRunMs?: number
  nextRunMs?: number
}

export interface NapiJobSchedule {
  jobId: string
  jobType: string
  state: string
  enabled: boolean
  strictIntervalCycle: boolean
  maxRuns?: number
  runCount: number
  lastRunMs?: number
  nextRunMs?: number
  nextRunsMs: Array<number>
}

export interface NapiScheduleInput {
  type: string
  runAtMs?: number
  everyMs?: number
  cronExpr?: string
  tz?: string
  payloadJson?: string
  jobId?: string
  strictIntervalCycle?: boolean
  count?: number
}

export interface ScheduleResult {
  id: string
}

export interface TimerConfigInput {
  tickMs?: number
  maxJobs?: number
  payloadMaxBytes?: number
  maxGlobalConcurrency?: number
  maxExecutionRecords?: number
  watchdogTimeoutMs?: number
  wallClockJumpThresholdMs?: number
  storeKind?: string
  sqlitePath?: string
  restoreOnStart?: boolean
}

export declare function weeklyOn(dow: number, hour: number, minute: number): string
